#default: &default
#  adapter: mysql2
#  encoding: utf8mb4
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password:
#  host: localhost

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: scraping_service_development

test:
  <<: *default
  database: scraping_service_test

production:
  <<: *default
  database: scraping_service_production
  username: scraping_service
  password: <%= ENV["SCRAPING_SERVICE_DATABASE_PASSWORD"] %>
